spring.application.name=recruitment-system

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:53765/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

app.jwt.secret=temporary-dev-secret-key-change-me-32chars-minimum
app.jwt.expiration-minutes=60