spring.application.name=recruitment-system

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

app.jwt.secret=temporary-dev-secret-key-change-me-32chars-minimum
app.jwt.expiration-minutes=60

app.s3.endpoint=http://localhost:8333
app.s3.region=us-east-1
app.s3.access-key=dummy
app.s3.secret-key=dummy
app.s3.bucket=cv-attachments